// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYK8m1JX20hVMilmKzM4sUcFBX18JgFg8',
    appId: '1:142841763058:web:b458e078a07cf179e62c6b',
    messagingSenderId: '142841763058',
    projectId: 'rotten-c2542',
    authDomain: 'rotten-c2542.firebaseapp.com',
    storageBucket: 'rotten-c2542.firebasestorage.app',
    measurementId: 'G-ZF4QVWPTH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLLQuemLEJ1m9gDhH4hNpUpnnH3vKe9CI',
    appId: '1:142841763058:android:a52bc2432ec7fcc2e62c6b',
    messagingSenderId: '142841763058',
    projectId: 'rotten-c2542',
    storageBucket: 'rotten-c2542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrC9Iml5-KF0VkHA3N8sREqa_IN55JKw',
    appId: '1:142841763058:ios:d0b0a6ed55084ee7e62c6b',
    messagingSenderId: '142841763058',
    projectId: 'rotten-c2542',
    storageBucket: 'rotten-c2542.firebasestorage.app',
    iosBundleId: 'com.example.rotten',
  );
}
